### ISSUE TITLE
Incompatible time.Time type

### ISSUE THREAD

**Issue by minhyannv** [showa-93/go-mask#6]
demo code:`package main

import (
	"fmt"
	"strings"
	"time"

	mask "github.com/showa-93/go-mask"
)

type Demo struct {
	Email      string    `mask:"emailMask"`
	createTime time.Time `mask:"timeMask"`
}

func CustomEmailMaskFunc(arg string, value string) (string, error) {
	atIndex := strings.Index(value, "@")
	if atIndex == -1 {
		return "", fmt.Errorf("no '@' symbol found in email")
	}
	localPart := value[:atIndex]
	maskedLocalPart := localPart[:1] + strings.Repeat("*", len(localPart)-1)
	return fmt.Sprintf("%s@%s", maskedLocalPart, value[atIndex:]), nil
}

func main() {
	masker := mask.NewMasker()
	masker.RegisterMaskStringFunc("emailMask", CustomEmailMaskFunc)
	data := &Demo{
		Email:      "example@email.com",
		createTime: time.Now(),
	}
	maskedData, err := masker.Mask(data)
	if err != nil {
		fmt.Println("Error masking data:", err)
		return
	}
	fmt.Printf("Original: %+v\n", data)
	fmt.Printf("Masked: %+v\n", maskedData)
}
`
output:`Original: &{Email:example@email.com createTime:{wall:13951653658314441720 ext:12877701 loc:0xd38640}}
Masked: &{Email:e******@@email.com createTime:{wall:0 ext:0 loc:<nil>}}`

The value of time is not retained. Is there a solution to this problem? Thank you

**Comment by showa-93** [comment]
Thank you for raising the issue.
Upon investigation, it was found that the private fields of time.Time were not being copied, resulting in zero values.
This has been fixed in version 0.6.2 to ensure that private fields are copied.
Please verify the changes. Thank you.

https://go.dev/play/p/-q7bVG7iTrO
